### ISSUE TITLE
NCCL backend did not start distributed training

### ISSUE THREAD

**Issue by YYStreet** [kubeflow/pytorch-operator#202]
I am trying to deploy distributed MNIST training on EKS by NCCL backend. However it seems like the NCCL does not work well. I use similar approach and success on GLOO backend

The message from master node:

```
Using CUDA
Using distributed PyTorch with nccl backend
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ../data/MNIST/raw/train-images-idx3-ubyte.gz
Extracting ../data/MNIST/raw/train-images-idx3-ubyte.gz
9920512it [00:00, 14787158.04it/s]                             
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to ../data/MNIST/raw/train-labels-idx1-ubyte.gz
Extracting ../data/MNIST/raw/train-labels-idx1-ubyte.gz
32768it [00:00, 770194.81it/s]
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to ../data/MNIST/raw/t10k-images-idx3-ubyte.gz
Extracting ../data/MNIST/raw/t10k-images-idx3-ubyte.gz
1654784it [00:00, 12384715.71it/s]                           
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to ../data/MNIST/raw/t10k-labels-idx1-ubyte.gz
Extracting ../data/MNIST/raw/t10k-labels-idx1-ubyte.gz
8192it [00:00, 314226.62it/s]
Processing...
Done!
kubeflow-pytorch-gpu-dist-job-master-0:1:1 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:192.168.4.230<0>
kubeflow-pytorch-gpu-dist-job-master-0:1:1 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
kubeflow-pytorch-gpu-dist-job-master-0:1:1 [0] NCCL INFO NET/IB : No device found.
NCCL version 2.4.7+cuda10.0
kubeflow-pytorch-gpu-dist-job-master-0:1:50 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff

```
And the message from worker node:

```
kubeflow-pytorch-gpu-dist-job-worker-0:1:1 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0> [1]eth0:192.168.34.106<0>
kubeflow-pytorch-gpu-dist-job-worker-0:1:1 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
kubeflow-pytorch-gpu-dist-job-worker-0:1:1 [0] NCCL INFO NET/IB : No device found.
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO Call to connect returned Connection refused, retrying
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO Call to connect returned Connection refused, retrying
...
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO Call to connect returned Connection refused, retrying
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] include/socket.h:387 NCCL WARN Connect to 127.0.0.1<57153> failed : Connection refused
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO transport/net_socket.cc:142 -> 2
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO bootstrap.cc:19 -> 2
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO bootstrap.cc:218 -> 2
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO init.cc:694 -> 2
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO init.cc:950 -> 2
kubeflow-pytorch-gpu-dist-job-worker-0:1:48 [0] NCCL INFO misc/group.cc:69 -> 2 [Async thread]
Traceback (most recent call last):
  File "/var/mnist.py", line 150, in <module>
    main()
  File "/var/mnist.py", line 138, in main
    model = Distributor(model)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: /tmp/pip-req-build-5kffdw2c/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error
```

Here are corresponding steps I am using to deploy the job
```
#/bin/bash

ks init pytorch-dist
cd pytorch-dist/
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/master/kubeflow
ks pkg install kubeflow/pytorch-job
ks generate pytorch-operator pytorch-operator

# Apply the component
ks apply default -c pytorch-operator

# Apply the distributed training job
kubectl apply -f /tmp/pytorch_multi_node_training.yaml
```

And the corresponding pytorch_multi_node_training.yaml looks like it:
```
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: kubeflow-pytorch-gpu-dist-job
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - args: 
            - --backend
            - nccl 
            - --epochs
            - '10'
            image: ***
            name: pytorch
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - args:
            - --backend
            - nccl
            - --epochs
            - '10' 
            image: ***
            name: pytorch
            resources:
              limits:
                nvidia.com/gpu: 1
```
The images I am using is something similar with the Dockerfile template available in this repo.
