### ISSUE TITLE
confusion about muti-gpu per one pod

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/pytorch-operator#331]
one master with 1 gpu, and two worker with 2gpu each.
when I submit the PytorchJob, I find the env WORLD_SIZE is 3, why is not 5?

```
apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-gloo"
  namespace: system
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: pytorch:1.0-cuda10.0-cudnn7-runtime
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              resources: 
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: pytorch:1.0-cuda10.0-cudnn7-runtime
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              resources: 
                limits:
                  nvidia.com/gpu: 2
```
