### ISSUE TITLE
PytorchJob replicas has different node affinity behaviors compared with Deployment

### ISSUE THREAD

**Issue by Shuai-Xie** [kubeflow/pytorch-operator#344]
Hello.

Dear developers, I find a problem when using pytorchjob.

## Problem

I notice that **PytorchJob replica pods don't obey the scheduling rules set in the node affinity. All the pods of a pytorchjob replica tend to be scheduled on the same node. And the preferred weights set in the node affinity seem to not affect**.

## Example: PytorchJob vs. Deployment

For example, the **PytorchJob** and **Deployment** replica pods are expected to be scheduled to `A1` and `A2` nodes, and 1 Pod is on `A1` while 2 Pods are on `A2`. 

The Yaml files are below.

- Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: machine
                operator: In
                values:
                - A1
                - A2
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: machine
                  operator: In
                  values:
                  - A1
            - weight: 2
              preference:
                matchExpressions:
                - key: machine
                  operator: In
                  values:
                  - A2
```

- PytorchJob

```yaml
apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-gloo"
  namespace: "default"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: pytorch-dist-mnist:1.0
              imagePullPolicy: IfNotPresent       
              resources: 
                limits:
                  nvidia.com/gpu: 1       
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers: 
            - name: pytorch
              image: pytorch-dist-mnist:1.0
              imagePullPolicy: IfNotPresent
              resources: 
                limits:
                  nvidia.com/gpu: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: machine
                    operator: In
                    values:
                    - A1
                    - A2
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                    - key: machine
                      operator: In
                      values:
                      - A1
                - weight: 2
                  preference:
                    matchExpressions:
                    - key: machine
                      operator: In
                      values:
                      - A2
```

It can be seen in the result that the preferred weights in the node affinity work well in **Deployment** but fail in **PytorchJob**. 

**I guess maybe the default replicas pods scheduling strategy tends to schedule pods to as fewer nodes ad possible so that it can benefit from the GPU communication when distributed training**.

```sh
$ k get pods -o wide
NAME                               READY   STATUS         RESTARTS   AGE   IP               NODE
# deployment replicas ok
myapp-798878df64-7r4wp             1/1     Running        0          3s    10.100.103.143   A1
myapp-798878df64-qc6nt             1/1     Running        0          3s    10.100.103.148   A2
myapp-798878df64-wr7l6             1/1     Running        0          3s    10.100.254.60    A2
# pytochjob replicas all on A2
pytorch-dist-mnist-gloo-worker-0   1/1     Running        0          61s   10.100.103.172   A2
pytorch-dist-mnist-gloo-worker-1   1/1     Running        0          61s   10.100.103.144   A2
pytorch-dist-mnist-gloo-worker-2   1/1     Running        0          61s   10.100.103.146   A2
```

Thanks a lot.
