### ISSUE TITLE
[bug]: pytorchjob status conditions out-of-order

### ISSUE THREAD

**Issue by codeflitting** [kubeflow/pytorch-operator#88]
![image](https://user-images.githubusercontent.com/6194419/47420135-4d8b7080-d7b0-11e8-907a-edad645007c6.png)

Created after Succeeded

**Comment by gaocegege** [comment]
Can you give us more details about it? I think conditions does not require order, we can only rely on the time field in them.

**Comment by codeflitting** [comment]
When the job just ended  the conditions is    
- Created -> Running -> Succeeded

After a while the conditions is 

- Running -> Succeeded -> Created


when the last conditions is succeeded，tf-operator wont update the conditions， i think this is a pytorch-operator bug

**Comment by gaocegege** [comment]
Gotcha, then I think so. And we should check it in tf-operator, too.

**Comment by johnugeorge** [comment]
I haven't seen this before.  I couldn't reproduce this issue. 
In the screenshot,  I see that lastUpdateTime of Create event(2018-10-24) is later than the other two.  How did it happen?

**Comment by codeflitting** [comment]
@johnugeorge 
```yaml
spec:
  cleanPodPolicy: None
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            helm.sh/namespace: test
            helm.sh/path: pytorchjob-1540278456
            helm.sh/release: pytorchjob-1540278456
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - python /mnist-pytorch/train.py
            image: pytorch:v0.4.1-py36
            name: pytorch
            ports:
            - containerPort: 23456
              name: pytorchjob-port
            resources:
              limits:
                nvidia.com/gpu: "0"
              requests:
                cpu: 500m
                memory: 512Mi
```
